### ISSUE TITLE
[Building MIRAI]  wrapper.h:1:10: fatal error: 'z3.h' file not found

### ISSUE THREAD

**Issue by yanliu18** [facebookexperimental/MIRAI#1157] opened 2022-06-21 00:43 UTC
## Issue

Run ```cargo install --locked --path ./checker``` failed due to 
```
failed to run custom build command for `z3-sys v0.7.1`
```

Caused by 
```
process didn't exit successfully: `<PATHTOMIRAI>/target/release/build/z3-sys-1ee5d02118b012a6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'z3.h' file not found
  wrapper.h:1:10: fatal error: 'z3.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/z3-sys-0.7.1/build.rs:33:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `mirai v1.1.0 (<PATHTOMIRAI>/checker)`, intermediate artifacts can be found at `<PATHTOMIRAI>/target`
```

## Steps to Reproduce
1. brew info z3 
```
z3: stable 4.8.17 (bottled), HEAD
High-performance theorem prover
https://github.com/Z3Prover/z3
/usr/local/Cellar/z3/4.8.17 (135 files, 94.9MB) *
  Poured from bottle on 2022-06-17 at 00:26:16
```
2. git clone https://github.com/facebookexperimental/MIRAI.git
3. cd MIRAI
4. ./setup.sh
5. cp binaries/libz3.dylib /usr/local/lib
```
cp: /usr/local/lib/libz3.dylib: Permission denied
```
manually copy succeeded, replaced the original ```libz3.dylib``` in ```/usr/local/lib```
6. cargo install --locked --path ./checker

## Expected Behavior

Successful build of MIRAI

## Actual Results

Panic

## Environment
macOS Monterey v12.3.1, Intel processor.
Rust version: rustc 1.63.0-nightly (4c5f6e627 2022-05-17)

**Comment by hermanventer** [comment] 2022-07-02 19:51
I wasn't able to replicate the failure to build z3-sys on my system, but I could induce a linker failure by uninstalling z3 from brew and by copying (using sudo) binaries/libz3.dylib to /usr/local/lib.

You can work around this by getting the correct version of libz3.dylib from the place where brew installs it. On my system that is /opt/homebrew/lib.

I'll update the checked in version of libz3.dylib, but I can't do it here in https://github.com/facebookexperimental/MIRAI because no-one at Meta wants to help me merge PRs. I'll do it in https://github.com/hermanventer/MIRAI, which should now be regarded as the source of truth for MIRAI.

**Comment by hermanventer** [comment] 2022-07-02 19:59
I believe this problem is already fixed on https://github.com/hermanventer/MIRAI, which should now be regarded as the source of truth for MIRAI since no-one at Meta seems interested in merging pull requests into this repo.

**Comment by hermanventer** [comment] 2022-07-12 22:42
Could you append a full log of a session where you follow the installation instructions and it fails?

**Comment by garbervetsky** [comment] 2022-07-12 23:34
@hermanventer This are the steps I followed: 
`./setup.sh` everything looks fine. 

```
 Installed package `cargo-audit v0.17.0` (executable `cargo-audit`)
info: using existing install for 'nightly-2022-05-18-x86_64-apple-darwin'
info: override toolchain for '<folderRemoved>/MIRAI' set to 'nightly-2022-05-18-x86_64-apple-darwin'
 Installed package `cargo-audit v0.17.0` (executable `cargo-audit`)
info: using existing install for 'nightly-2022-05-18-x86_64-apple-darwin'
info: override toolchain for '/<folderRemoved>/MIRAI' set to 'nightly-2022-05-18-x86_64-apple-darwin'

  nightly-2022-05-18-x86_64-apple-darwin unchanged - rustc 1.63.0-nightly (4c5f6e627 2022-05-17)
```

Then: 
`cargo install --locked --path ./checker`

```
  Installing mirai v1.1.0 (<folderRemoved>/MIRAI/checker)
  Updating crates.io index
  Downloaded peeking_take_while v0.1.2
....
Compiling z3-sys v0.7.1
error: failed to run custom build command for `z3-sys v0.7.1`

Caused by:
  process didn't exit successfully: `<folderRemoved>/MIRAI/target/release/build/z3-sys-1ee5d02118b012a6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  wrapper.h:1:10: fatal error: 'z3.h' file not found
  wrapper.h:1:10: fatal error: 'z3.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()',˜ /.cargo/registry/src/github.com-1ecc6299db9ec823/z3-sys-0.7.1/build.rs:33:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mirai v1.1.0 (<folderRemoved>/MIRAI/checker)`, intermediate artifacts can be found at `<folderRemoved>/MIRAI/target`
`

**Comment by hermanventer** [comment] 2022-07-13 00:10
From InstallationGuide.md:

For macOS the binary will have to be placed somewhere where it can be found and dynamically loaded by the Rust runtime.
You'll also need the z3 header files.

On an Intel Mac, do

```bash
sudo cp binaries/libz3.dylib /usr/local/lib
sudo cp include/*.h /usr/local/include
```

**Comment by garbervetsky** [comment] 2022-07-13 00:28
Make senses. I did copied the library but not the include files because is not in the instructions :-)
Thanks @hermanventer

**Closed** 2022-09-18 00:28 UTC

**Comment by ukcw** [comment] 2023-01-17 03:32
Hi, where would I need to place the files on an ARM Mac?

**Comment by hermanventer** [comment] 2023-01-17 04:05
This step is no longer required. You can just build MIRAI. See the current installation guide.

**Comment by ukcw** [comment] 2023-01-17 04:21
Hi @hermanventer, I'm installing the `z3` package for another project I'm working with and have the same issue as above. I need some help because the `/include` files are not on the PATH I believe?

**Comment by hermanventer** [comment] 2023-01-17 06:21
Z3 is now statically linked into MIRAI, so there is no dependency or interference  from any other Z3 package you may have.
