### ISSUE TITLE
Developer Guide should mention specific nightly date

### ISSUE THREAD

**Issue by int3** [facebookexperimental/MIRAI#83] opened 2019-02-24 07:29 UTC
It says to do `rustup override set nightly` but as of 02/23 this results in `cargo build` failing with a compile error. I eventually realized that the Travis build was pinned to the 01/07 nightly. Maybe the guide could contain a pointer to the `.travis.yml` file?

FWIW, before realizing that, I had cobbled together a fix to make things compile here: https://github.com/int3/MIRAI/commit/f4a45d2827cd42adbb58b2b05842dad5523b64e5.

Edit: The "fix" errors out at runtime, never mind... just going to work off the older nightly version for now.

**Comment by hermanventer** [comment] 2019-02-24 21:00
I'm sorry that you that your first experience of Mirai has been problematic. The runtime issue with the nightly build has been pending since soon after 01/07. The build issue is addressed in PR #58.

I have recently had a bit of time to investigate the runtime issue and confirmed my suspicion that it is caused by the RocksDB crate. I'm looking into swapping that dependency for an all Rust persistent KV store. Hopefully that will fix the nightly problem. It remains to be seen if the Z3 dependency that I'm currently working on will be equally problematic.

if you do want to use the latest nightly, you can use the new_nightly branch. The master branch, together with your patch will also work on a Mac.

**Closed** 2019-02-25 18:46 UTC
